### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ycjcl868** [ahmedelgabri/gatsby-plugin-klipse#1] opened 2019-02-06 06:38 UTC
![image](https://user-images.githubusercontent.com/13595509/52324596-de632080-2a1c-11e9-8aeb-6bd5fddde617.png)

**Comment by ahmedelgabri** [comment] 2019-02-08 20:06
@ycjcl868 	more context or info is going to be helpful, so please provide more context or maybe even a small reproducable steps. Thanks.

**Comment by malcolm-kee** [comment] 2019-03-18 07:12
I actually found the root cause for this. The problem is klipse script is currently attaching its variable in `window` object, and it somehow replace the `window.io` variable, which causing the gatsby socket io js being replaced. You can see the klipse bug here: https://github.com/viebel/klipse/issues/330

**Comment by ahmedelgabri** [comment] 2019-03-18 09:19
Thanks @malcolm-kee! will look into it soon 👍

**Comment by ahmedelgabri** [comment] 2020-05-21 18:33
This should be fixed in `7.0.0`

**Closed as completed by ahmedelgabri** 2020-05-21 18:33 UTC
